require('dotenv').config()

const express = require('express')
const nodemailer = require('nodemailer')
const router = express.Router()

// Configure Nodemailer
const transporter = nodemailer.createTransport({
  service: 'Gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
})

// Contact form submission endpoint
router.post('/', async (req, res) => {
  const { name, email, message } = req.body

  const mailOptions = {
    to: process.env.ADMIN_EMAIL, // Admin's email address
    subject: `New Contact Form Submission from ${name}`,
    text: `You have a new message from the contact form:
  
  Name: ${name}
  Email: ${email}
  Message: ${message}`,
    html: `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #4a90e2; color: #fff; padding: 16px; text-align: center; font-size: 18px; font-weight: bold;">
          New Contact Form Submission
        </div>
        <div style="padding: 16px;">
          <p style="margin: 0 0 8px;"><strong>Name:</strong> ${name}</p>
          <p style="margin: 0 0 8px;"><strong>Email:</strong> <a href="mailto:${email}" style="color: #4a90e2; text-decoration: none;">${email}</a></p>
          <p style="margin: 0 0 8px;"><strong>Message:</strong></p>
          <div style="background-color: #f9f9f9; padding: 12px; border-radius: 4px; border: 1px solid #ddd;">
            ${message}
          </div>
        </div>
        <div style="text-align: center; font-size: 12px; color: #888; padding: 16px; background-color: #f5f5f5;">
          This email was automatically generated by your contact form.
        </div>
      </div>
    `,
  }

  try {
    await transporter.sendMail(mailOptions)
    res.json({ success: true, message: 'Message sent successfully' })
  } catch (error) {
    console.error('Error sending email:', error)
    res.json({ success: false, message: 'Failed to send message' })
  }
})

module.exports = router
